/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import lombok.Getter;
import lombok.Setter;
import lombok.AccessLevel;

@Getter
public class App {
    public String getGreeting() {
        GetterSetterExample ex = new GetterSetterExample();
        System.out.println(ex.getAge());
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}

class GetterSetterExample {

    @Getter
    @Setter
    private int age = 10;

    @Setter(AccessLevel.PROTECTED)
    private String name;

    @Override
    public String toString() {
        return String.format("%s (age: %d)", name, age);
    }
}
